name: polestar

version: "3.9"

services:
  webpack-watch-link:
    build:
      context: .
      dockerfile: Dockerfile
    image: webpack-watch-link:latest
    container_name: webpack-watch-link
    mem_limit: 4g
